### ISSUE TITLE
very slow today

### ISSUE THREAD

**Issue by johneightyone** [ehmorris/lunar-lander#12]
something seems to have changed, i tried in both edge and brave, and the game now runs too slow to be playable.

**Comment by santiagobasulto** [comment]
Yes, I can confirm. Very slow for me as well. Running on Chrome+Mac.

**Comment by abrudz** [comment]
Same on Firefox/Windows.

**Comment by jaiverma** [comment]
+1
Working fine on iOS on Safari, but very slow on Windows (Chrome and Edge).

**Comment by ehmorris** [comment]
I added some noise to the background that was probably slowing down each frame. I've removed it. let me know if things are feeling faster tomorrow.

**Comment by johneightyone** [comment]
yep, back to normal now!
